export const baseURL = "http://192.168.1.20:3000";
export const SIGNIN = `${baseURL}/signin`;
export const SIGNUP = `${baseURL}/signup`;
export const GETMOVIE = `${baseURL}/movie`;
export const CREATEGENRE = `${baseURL}/genre`;
export const GETGENRE=`${baseURL}/genre`
export const UPDATEGENRE=`${baseURL}/genre`
export const DELETEGENRE=`${baseURL}/genre`
export const IMAGEUPLOAD=`${baseURL}/upload`
export const VIDEOUPLOAD=`${baseURL}/video-upload`
